name: Release

on:
  workflow_call:
    inputs:
      semantic-release-version:
        description: The version of semantic-release to use.
        default: 25.0.2
        required: false
        type: string
      semantic-release-plugin-git-version:
        description: The version of the semantic-release git plugin to use.
        default: 10.0.1
        required: false
        type: string
      semantic-release-plugin-conventionalcommits-version:
        description: The version of the semantic-release conventional-changelog-conventionalcommits plugin to use.
        default: 9.1.0
        required: false
        type: string
    outputs:
      new-release-published:
        description: Whether or not a new version has been released.
        value: ${{ jobs.release.outputs.new-release-published }}
      new-release-version:
        description: The new release version number.
        value: ${{ jobs.release.outputs.new-release-version }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    # Skip running release workflow on forks
    if: github.repository_owner == 'craigsloggett-lab'
    outputs:
      new-release-published: ${{ steps.release.outputs.new_release_published }}
      new-release-version: ${{ steps.release.outputs.new_release_version }}
    steps:
    - name: Checkout
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Release
      id: release
      uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
      with:
        semantic_version: ${{ inputs.semantic-release-version }}
        extra_plugins: |
          @semantic-release/git@${{ inputs.semantic-release-plugin-git-version }}
          conventional-changelog-conventionalcommits@${{ inputs.semantic-release-plugin-conventionalcommits-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
