name: Publish

on:
  workflow_call:
    inputs:
      hcp-terraform-organization:
        description: The name of the HCP Terraform organization the Terraform module is being published to.
        required: true
        type: string
    secrets:
      hcp-terraform-api-token:
        description: The API token used to publish the Terraform module to a Private Module Registry.
        required: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    # Skip running release workflow on forks
    if: github.repository_owner == 'craigsloggett-lab'
    env:
      HCP_TERRAFORM_ORGANIZATION: ${{ inputs.hcp-terraform-organization }}
      TF_TOKEN_app_terraform_io: ${{ secrets.hcp-terraform-api-token }}
    steps:
    - name: Checkout
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Get Module Metadata
      id: get-module-metadata
      run: |
        github_repository_url="${{ github.server_url }}/${{ github.repository }}"
        authorization_header="Authorization: Bearer ${TF_TOKEN_app_terraform_io}"
        list_modules_endpoint="https://app.terraform.io/api/v2/organizations/${HCP_TERRAFORM_ORGANIZATION}/registry-modules"

        module_json="$(
          curl --request GET --header "${authorization_header}" "${list_modules_endpoint}" |
            jq -r --arg repository_http_url "${github_repository_url}" '.data[]
              | select(.attributes["vcs-repo"]["repository-http-url"]
              | contains($repository_http_url))'
        )"
        module_name="$(printf '%s\n' "${module_json}" | jq -r '.attributes.name')"
        module_provider="$(printf '%s\n' "${module_json}" | jq -r '.attributes.provider')"

        printf '%s\n' "${module_name}"
        printf '%s\n' "${module_name}"

        printf 'name=%s\n' "${module_name}" >> "$GITHUB_OUTPUT"
        printf 'provider=%s\n' "${module_provider}" >> "$GITHUB_OUTPUT"
    - name: Publish
      run: |-
        module_name="${{ steps.get-module-metadata.outputs.name }}"
        module_provider="${{ steps.get-module-metadata.outputs.provider }}"
        module_version="0.12.1"
        commit_sha="65ab3aa3abdb0d5c9c9f7353f2700bde5bb3ffc3"
        cat << EOF > payload.json
          {
            "data": {
              "type": "registry-module-versions",
              "attributes": {
                "version": "${module_version}",
                "commit-sha": "${commit_sha}"
              }
            }
          }
        EOF

        authorization_header="Authorization: Bearer ${TF_TOKEN_app_terraform_io}"
        content_type_header="Content-Type: application/vnd.api+json"

        registry_modules_url="https://app.terraform.io/api/v2/organizations/${HCP_TERRAFORM_ORGANIZATION}/registry-modules/private"
        create_module_version_endpoint="${registry_modules_url}/${HCP_TERRAFORM_ORGANIZATION}/${module_name}/${module_provider}/versions"

        curl \
          --header "${authorization_header}" \
          --header "${content_type_header}" \
          --request POST \
          --data @payload.json \
          "${create_module_version_endpoint}"
